### PR TITLE
Fix XS missing 'ctx' into context

### LINKED ISSUE #72: Subscription and service level resolver
My problem is when I define resolvers in settings with graphql, resolvers works as expected when I call a query. But when I call subscriptions resolvers do not work.

This is the example definition:
```
graphql: {
    type: [
        Employee,
        EmployeeList,
        Address,
        Phone,
        Email,
        AddressInput,
        PhoneInput,
        EmailInput,
    ],
    resolvers: {
        Employee: {
            gender: {
                action: "genders.read",
                rootParams: {
                    gender: "code",
                },
            },
            maritalStatus: {
                action: "maritalStatuses.read",
                rootParams: {
                    maritalStatus: "code",
                },
            },
        },
        Address: {
            streetType: {
                action: "streetTypes.read",
                rootParams: {
                    streetType: "code",
                },
            },
        },
    },
},
```
Do I need to define other resolvers for subscriptions? I haven't found any example of using resolvers with subscriptions.

This works in the http://localhost:3000/graphql:
```
query {
  employee(code: "0000000017") {
    code
    gender {
      code
    }
  }
}
```
But this doesn't:
```
subscriptions {
  employee(code: "0000000017") {
    code
    gender {
      code
    }
  }
}
```
Sorry but I don't understand.
Thx

### PR DESCRIPTION
**Pull request by Hugome**
Fix #72

### CODE REVIEW

**Comment by shawnmcknight** [comment]
I'm trying to get myself a bit more familiar with subscriptions and web sockets here, but I have a couple thoughts so far:

1)
```js
                  : {
                      service: connection.$service,
                    };
              },
              subscriptions: {
                onConnect: connectionParams => ({
                  ...connectionParams,
                  $service: this,
                }),
              },
```

In inspecting what happens here, the `onConnect` handler will add `$service` to the graphql context.  However, this is not available at `connection.$service` later, but is instead available at `connection.context.$service`.  Nothing appears to actually make use of this in the rest of the code, but I think this is incorrect and plays into my next thought.

2) Perhaps instead of establishing a new `Context` instance in the `context` assignment, it should instead be created when the subscription connects.  Something like you already did, but add `$ctx` to the result of `onConnect` and then set `ctx` to `connection.context.$ctx` in the object construction.

3) I think setting the empty `dataLoaders` Map in both context objects would be important.  If a child resolver had the dataLoader flag set, we would end up failing similarly to `ctx` being missing.

4) If we create a new `Context` here, it would seem that the `asyncIteratorResolver` could use `ctx.call` instead of `broker.call` which is a little smoother in my opinion.

5) If the WS logic is bypassing `moleculer-web`'s assignment of the `$` internal variables and creation of context, are we ultimately bypassing everything else `moleculer-web` abstracts away?  That is, are we bypassing all of the lifecycles like `authentication` and `authorization`?  I'm guessing we are, which is concerning.  I'm not sure if there's a way to remedy that, but if it can be remedied, is there a manner in which the creation of context can be moved into `moleculer-web`'s functionality in some way, similar to how the context is added to the `req` by `moleculer-web`?

As I mentioned in my opening, I'm not terribly familiar with GraphQL subscriptions or web sockets in general as I've not used either, but I wanted to get my initial thoughts on the table.  I'll dig in some more.

**Comment by shawnmcknight** [comment]
>If the WS logic is bypassing moleculer-web's assignment of the $ internal variables and creation of context, are we ultimately bypassing everything else moleculer-web abstracts away? That is, are we bypassing all of the lifecycles like authentication and authorization? I'm guessing we are, which is concerning. I'm not sure if there's a way to remedy that, but if it can be remedied, is there a manner in which the creation of context can be moved into moleculer-web's functionality in some way, similar to how the context is added to the req by moleculer-web?

So, after digging in a bit here, that's where `onConnect` is supposed to come into play.  If you need custom authentication/authorization logic, that needs to occur here.  It appears that you can intercept http headers for something like a token.  So, I'm thinking in order to solve _that_, a different injectable function would need to be provided that could run as part of the connection lifecycle.  Clearly that's out of scope for this PR.

With that in mind, I am more of the opinion that establishing context in `onConnect` is a more suitable location.  Also, as I dig a bit more into how the service broker creates context, it uses the broker's factory method to do it, which I believe is important for custom contexts (we use one in our environment). so it would be risky to not ensure that is used.  So maybe @icebob should weigh in here if there is a better way, but I'm thinking `ctx = this.broker.ContextFactory.create(this, null, {}, {});` might be the more appropriate way to generate context at this level.

**Comment by icebob** [comment]
Yes, using the ContextFactory.create is the right way to create context. Moreover, if you don't define `Endpoint` it maybe causes problems. But you can't because the Context created outside actions. _Maybe we can create an internal action like moleculer-web has also a `rest` internal action which is called with `req` & `res`. Although, I'm not familiar with Apollo subscription._

**Comment by Hugome** [comment]
@shawnmcknight 

> Perhaps instead of establishing a new Context instance in the context assignment, it should instead be created when the subscription connects. Something like you already did, but add $ctx to the result of onConnect and then set ctx to connection.context.$ctx in the object construction.

> I think setting the empty `dataLoaders` Map in both context objects would be important.  If a child resolver had the dataLoader flag set, we would end up failing similarly to `ctx` being missing.

> If we create a new Context here, it would seem that the asyncIteratorResolver could use ctx.call instead of broker.call which is a little smoother in my opinion.

Yep you are totally right with these points.

@icebob 

> Maybe we can create an internal action like moleculer-web has also a rest internal action which is called with req & res. Although, I'm not familiar with Apollo subscription.

I think it can do the job quite well.

I have change the code, let me know what you think.
It use this idea of @icebob and improve the context (Now you can have access to the query params passed to the upgrade request if your need in you authentification/autorization) 
And apply @shawnmcknight improvement on connection.context.$ctx/dataLoaders/asyncIteratorResolver

**Comment by icebob** [comment]
@shawnmcknight could you help to check it?

File: src/service.js [hunk 1]
```diff
@@ -28,6 +28,26 @@ module.exports = function(mixinOptions) {
...
+				tracing: {
+					tags: {
+						params: [
+							"socket.upgradeReq.url"
+						]
+					},
+					spanName: ctx => `UPGRADE ${ctx.params.socket.upgradeReq}`
+				},
+				handler(ctx) {
+					const { socket, connectionParams } = ctx.params
```
Comment (shawnmcknight) [inline src/service.js:43]: Can you run a lint against this file?  I'm seeing some errors reported (e.g. no semi at the end of this line).

File: src/service.js [hunk 2]
```diff
@@ -586,22 +605,23 @@ module.exports = function(mixinOptions) {
...
+									params: connection.context.socket.$params,
+								}),
+								dataLoaders: new Map(), // create an empty map to load DataLoader instances into
+							}),
 							subscriptions: {
-								onConnect: connectionParams => ({
-									...connectionParams,
-									$service: this,
+								onConnect: async (connectionParams, socket) => ({
+									...await this.actions.ws({ connectionParams, socket }),
```
Comment (shawnmcknight) [inline src/service.js:622]: My instinct here is that there really isn't much of an advantage to mutating `socket` since the end result of all of this is to just add the resulting object on to context.  I feel like the `ws` action parameter signature is good as it will afford a lot of flexibility.  However, it seems like we could just return the full object that will become `context` from there, rather than mutating `socket` and using it.

That is, return an object with `ctx`, `service`, and `params` on it from the action and make that the return value from `onConnect`.  Is there an advantage to this approach that maybe I am not immediately seeing?

File: src/service.js [hunk 3]
```diff
@@ -303,14 +323,13 @@ module.exports = function(mixinOptions) {
...
+								async (payload, params, { ctx }) =>
 									payload !== undefined
-										? this.broker.call(filter, { ...params, payload }, ctx)
+										? ctx.call(filter, { ...params, payload })
 										: false
 						  )
 						: () => this.pubsub.asyncIterator(tags),
-					resolve: async (payload, params, ctx) =>
-						this.broker.call(actionName, { ...params, payload }, ctx),
+					resolve: async (payload, params, { ctx }) => ctx.call(actionName, { ...params, payload })
```
Comment (shawnmcknight) [inline src/service.js:332]: Since `ctx.call` returns a `Promise`, making these functions `async` is unnecessary.

File: src/service.js (hunk 1 above)
Comment (Hugome) [reply src/service.js]: Oh sorry I forget to check that before push, done.

File: src/service.js (hunk 2 above)
Comment (Hugome) [reply src/service.js]: The idea was to keep the same concept as moleculer-web (Where `req` & `res` are populated with `$ctx`). If anybody need to access the molculer context outside (Let's say some kind of magic ws middleware).
But your right, there is no other direct advantages other than keeping the moleculer-web approch, we can make the return value of `onContext` the action return value.
To me both approch seem good, what to you think ?

Comment (shawnmcknight) [reply src/service.js]: Sorry, I'm just getting back to this now.  I do feel like the side-effecty behavior of the `ws` action mutating `socket` lends to a less understandable structure for it.  I think it would definitely be preferable to simply have it construct all of the `$xyz` variables that would ultimately become the `connection.context` object.

So this is what I'm thinking for the API on the `ws` action:

Input Params:
* `connectionParams`
* `socket`

Output Object:
```js
{
  $ctx: <Moleculer context>
  $socket: <Original socket parameter>
  $service: this,
  $params: <see more below>
}
```

With this structure, I feel like a consumer could wrap the `ws` action with hooks or middlewares and get access to everything provided on the way in (in a before-hook scenario) and also access a consistent payload of everything available on the way out (in an after-hook scenario).  My inclination is this might also put a path forward to alllowing consumers to solve for `authentication` issues by wrapping this action in a hook.  In our environment today we use `moleculer-web`'s `authentication` method to validate a JWT and then enrich `ctx.meta` with information.  I feel like a consumer here could wrap the `ws` method and implement whatever they wanted to for the websocket connections.

Back to `$params` for a minute.  I think it's a good idea, for consistency purposes, to provide a `$params` so it remains in a similar format to what happens on a normal request.  I do question whether `body` makes sense here though.  From what I'm understanding, `connectionParams` is more akin to request headers (please correct me if I'm wrong) than it would be to a body.  I'm not sure if it naturally is more like a `body` or `headers` but at least when I was playing in the GraphQL playground it seemed that I was able to specify this information in the `headers` input area.  I do see that `socket.upgradeReq` has its own `headers` property though, so there's a pretty good chance I'm off base here.

With respect to `socket.upgradeReq.query`, I'm not seeing that as a defined property on `socket.upgradeReq`.  Is there a scenario where this can be populated?

Comment (Hugome) [reply src/service.js]: Hey, sry for late reply,
After typing the code you're definitely right, this is more clean than mutating the socket, just one place where `$xyz` are built.

`$params` case
`connectionParams` should be based on the first message sent by the gql/web-socket client.
image
This is why I thought of a "body", but this can also by considered as headers in a sense where this is send only at the beginning of the ws session, as you want for the final implementation.

For `query`, this one is really for specific use cases where you want to send data before the `connection_init` message.
A non related example is with "SignalR", the client send a bunch of information in the query (Excluding the auth token) : 
image

**Comment by icebob** [comment]
What's the status of his PR?

File: src/service.js [hunk 4]
```diff
@@ -586,23 +607,23 @@ module.exports = function(mixinOptions) {
...
 											ctx: req.$ctx,
 											service: req.$service,
 											params: req.$params,
-											dataLoaders: new Map(), // create an empty map to load DataLoader instances into
 									  }
 									: {
-											service: connection.$service,
-									  };
-							},
+											ctx: connection.context.socket.$ctx,
```
Comment (shawnmcknight) [inline src/service.js:618]: Shouldn't this now be `ctx: connection.context.$ctx`?

File: src/service.js [hunk 5]
```diff
@@ -586,23 +607,23 @@ module.exports = function(mixinOptions) {
...
+											service: connection.context.$service,
+											params: connection.context.socket.$params,
```
Comment (shawnmcknight) [inline src/service.js:620]: Shouldn't this now be `params: connection.context.$params`?

**Comment by Hugome** [comment]
Absolutely right, now fixed

File: test/unit/service.spec.js [hunk 6]
```diff
@@ -1442,10 +1442,21 @@ describe("Test Service", () => {
 			expect(
 				contextFn({
 					connection: {
-						$service: "service",
+						context: {
+							$service: "service",
+							socket: {
+								$ctx: "context",
```
Comment (shawnmcknight) [inline test/unit/service.spec.js:1448]: Saw that the CI failed here.  The `$ctx` and `$params` need to be moved up a level now.

**Comment by Hugome** [comment]
Sorry I forgot to commit test file, done.

**Comment by icebob** [comment]
Awesome, thanks @shawnmcknight & @Hugome!
